### ISSUE TITLE
Repeated logouts

### ISSUE THREAD

**Issue by ediooo** [mifi/SimpleInstaBot#194] opened 2022-10-27 14:25 UTC
Since a few days I am getting repeated logouts.
So far it worked to simply login again and accept/confirm all logins in login activity within the instagram app.
However, now it does not let me login again.
I used very conservative settings less than 40 daily follows/unfollows, 20 likes per day etc.
The bot also stops as expected in the afternoon and starts again in the morning.

Have there been changes in Instagram that cause this behaviour?
Since I am already using very low settings I am not sure if this means the bots simply does not work at the moment?

**Comment by mifi** [comment] 2022-10-27 17:35
closing in favor of #191 - please continue discussion there.
I'm not aware of any changes, other than the new unfollow dialog which I'm not able to reproduce. Other than that I haven't received any indication that the bot is currently broken for most people

**Closed by mifi** 2022-10-27 17:35 UTC
