### ISSUE TITLE
Is this still working reliably for anyone?

### ISSUE THREAD

**Issue by ediooo** [mifi/SimpleInstaBot#234] opened 2023-04-07 19:29 UTC
In the past months I have not been able to use any of the bots functions with extremely conservative settings for more than 6 hours without getting action blocked. 
Even though I took all sorts if precautions: no additional devices logged in, static IP, latest version, long breaks before trying the bot again, old and non-spammy Ig account… 
Is anyone actually using this without issues and if so what is your secret and/or config file setup?

**Comment by mifi** [comment] 2023-04-08 02:50
Duplicate of #1

**Closed by mifi** 2023-04-08 02:50 UTC
