### ISSUE TITLE
TimeoutError: Navigation timeout of 30000 ms (On accounts that do exists)

### ISSUE THREAD

**Issue by NicolasMazzoleni** [mifi/SimpleInstaBot#150] opened 2022-07-13 20:41 UTC
**To Reproduce**
Currently running the 1.10.7 version on a Ubuntu remote server

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser : Chrome
 - Version : -

**Additional context**
When the bot start to reach the supposed new follower account page, the request timeout. It does happen randomly.
BY THE WAY, when I go to https://www.instagram.com/tangiers.to.auckland/ using Brave Browser, the page cannot be found either. Very weird, because it's working from the mobile app. 

<img width="606" alt="Screenshot 2022-07-13 at 10 38 14 PM" src="https://user-images.githubusercontent.com/34337703/178830194-ffe9d301-642a-4442-8eee-d81d260ac1f9.png">
sier for me to understand why it's failing, please copy and share with me the HTML of the button (or even better the whole page) and share it, by following these instructions:

- Make sure you run the command after getting the error message
- make sure that you open the dev tools **on the correct window (the instagram page)**

Use <kbd>Option</kbd> + <kbd>⌘</kbd> + <kbd>J</kbd> (on macOS), or <kbd>Shift</kbd> + <kbd>CTRL</kbd> + <kbd>J</kbd> (on Windows/Linux) to open devtools.

Using the Web Inspector (F12), go to the Elements tab, right click on the tag in your code and select Copy->Copy outerHTML. Then paste that here

If you feel it's private information you can instead email to simpleinstabot@yankee.no

**Comment by mifi** [comment] 2022-07-14 04:01
i think what you're asking is  for the bot to retry if it hits a timeout. closing as duplicate of #54

**Closed by mifi** 2022-07-14 04:01 UTC
