### ISSUE TITLE
Page isnt available

### ISSUE THREAD

**Issue by Sergej99** [mifi/SimpleInstaBot#182] opened 2022-10-02 15:47 UTC
Hey after some time using the bot, when it goes to instagram.com/@ANYUSERNAME , I get this page: https://prnt.sc/3UA8UDbqmLPd

But I don't get any action blocks, does someone know why is this and how can it be solved?

These are my parametres: 

{
  userAgent: '',
  maxFollowsPerDay: 300,
  maxFollowsPerHour: 40,
  maxLikesPerDay: 200,
  maxLikesPerUser: 0,
  enableFollowUnfollow: true,
  followUserRatioMin: 0.2,
  followUserRatioMax: 4,
  followUserMaxFollowers: null,
  followUserMaxFollowing: null,
  followUserMinFollowers: null,
  followUserMinFollowing: 10,
  dontUnfollowUntilDaysElapsed: 30,
  runAtHour: 10,
}

Please help , thanks in advance

**Comment by saabtech** [comment] 2022-10-10 06:59
its obvious, the user has changed the username or probably the account is disabled. Check the username of the account manually.

**Comment by mifi** [comment] 2022-10-10 15:33
I think duplicate of #142

**Closed by mifi** 2022-10-10 15:33 UTC
