### ISSUE TITLE
Many request bug - "Got 429 Too Many Requests, waiting..."

### ISSUE THREAD

**Issue by mmates** [mifi/SimpleInstaBot#117] opened 2022-03-12 18:13 UTC
**To Reproduce**
Bug sets up fairly quickly. Within two minutes, the shoe gets stuck.

**Screenshots**
![Screenshot 2022-03-12 184732](https://user-images.githubusercontent.com/31419423/158029709-60476e9c-0343-41fd-8a80-fa6f139dc165.png)
![Screenshot 2022-03-12 184646](https://user-images.githubusercontent.com/31419423/158029712-d28c4df8-b0e6-4e18-a2fe-c11c136a1a15.png)

**Log file**
[log.txt](https://github.com/mifi/SimpleInstaBot/files/8238132/log.txt)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 1.9.0

**Additional context**
The bug started appearing during the day. The values for "bot" are set very appropriately. I tried to "Bot" off and on again after a few hours. I read in previous issues that something like this has already been solved. Anyway, it's right for me to write it here again. Because the problem is not solved by turning off the "bot".

**Provide me with HTML**
[html.txt](https://github.com/mifi/SimpleInstaBot/files/8238131/html.txt)

**Comment by mifi** [comment] 2022-03-13 06:16
hi. thanks for reporting, but this is a duplicate of #59 - please continue discussion there
I think stopping it for a few hours is not enough. you may have to wait a few days, and use the mobile app from the same IP address for a few days so that instagram can flag you as "non-bot" again

**Closed by mifi** 2022-03-13 06:16 UTC
