### ISSUE TITLE
Can I somehow run it on multiple accounts in the same time? 

### ISSUE THREAD

**Issue by beetlejuice-hub** [mifi/SimpleInstaBot#51] opened 2021-02-17 13:01 UTC
First, thank you so much for the software, it works like a charm. One problem that I have a couple more instagram account. Is there a way to make the program work with more than one acount at the same time? (sorry for the english, I hope you understand what I wanted to say).

**Comment by beetlejuice-hub** [comment] 2021-02-17 13:02
I'm on Windows btw

**Comment by mifi** [comment] 2021-02-17 20:13
hi. this is a duplicate of #27

**Closed by mifi** 2021-02-17 20:13 UTC
